spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 956943295141-nqp017m6q0crvasjv66rkmc8bvb16faj.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          kakao:
            client-id: 25e685248b7c5653fc354f39aa148bb1
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
          naver:
            client-id: J6MjDCy6Pn6198FpQAk0
            client-secret: p3P0dvjNUk
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}" # (== http://localhost:8080/login/oauth2/code/naver)
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response